apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-service
  labels:
    app: crypto-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-service
  template:
    metadata:
      labels:
        app: crypto-service
    spec:
      containers:
        - name: crypto-service
          image: crypto-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto-service-secret
                  key: JWT_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /openapi.json
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /openapi.json
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
