apiVersion: v1
kind: Service
metadata:
  name: crypto-service
  labels:
    app: crypto-service
spec:
  type: NodePort
  selector:
    app: crypto-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080